# Generated by Django 4.2.17 on 2024-12-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_names',
            new_name='category_name',
        ),
    ]
