# Generated by Django 4.2.17 on 2024-12-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
